### ISSUE TITLE
Feature vote

### ISSUE THREAD

**Issue by Mrcomputer1** [Mrcomputer1/PostCountProgressBar#1]
Do you want custom color selection or language changing?

Please vote here: https://docs.google.com/forms/d/1PVt9Tf6T7kXuHYRUprO5f1NbsefSjI3ztkdI_s7R0Xo/viewform

**Update (14/10/15) [Things I forgot to say]**: Vote closes 23/10/15, Top 3 items picked to be added

**Comment by coder6a** [comment]
Custom color, definitely!

**Comment by iliketocode** [comment]
I voted!

**Comment by Mrcomputer1** [comment]
@iliketocode Thanks for voting! :smile:
