### ISSUE TITLE
Make sure script.js loads when the document finishes loading.

### ISSUE THREAD

**Issue by colinator27** [Mrcomputer1/PostCountProgressBar#9]
If you look in the console, it says that $ is undefined.

I would recommend putting an if statement that detects when the DOM is finished loading.

This kind of thing:

    window.addEventListener("onload", function () {/* your code here */}, false);

**Comment by Mrcomputer1** [comment]
Ok I will fix this later because I don't have time to do it right now.

**Comment by Mrcomputer1** [comment]
I think I have fixed it.

@colinator27 Can you please confirm this?
